### ISSUE TITLE
The squared social Buttons and Rounded social buttons should be separated for clear UI

### ISSUE THREAD

**Issue by dsnehasish74** [shahednasser/sbuttons#270] opened 2020-09-27 17:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional notes**
![Screenshot (162)](https://user-images.githubusercontent.com/58779604/94371723-41378d00-0116-11eb-8411-9b0cf7a47315.png)

**Comment by dsnehasish74** [comment] 2020-09-27 17:46
I want to work on this can I?????

**Comment by Neeraj3508** [comment] 2020-09-28 05:26
I thought of same but isn't it better if they are side by side and user can see differences?

**Comment by dsnehasish74** [comment] 2020-09-28 07:01
Might be but in the page every button is separated by its square and rounded . So it is looking odd ............. is not it????

**Comment by Neeraj3508** [comment] 2020-09-28 07:06
Everyone has their own views. I think admin should decide what to do, yeah but we can do give suggestions though.

**Comment by dsnehasish74** [comment] 2020-09-28 09:30
Yup

**Comment by shahednasser** [comment] 2020-09-28 12:11
@Neeraj3508 and @dsnehasish74 I've commented on this [here](https://github.com/shahednasser/sbuttons/issues/271#issuecomment-699958439). @dsnehasish74 let me know if you can work on it as I described it there. If not, maybe @Neeraj3508 would like to work on it. Let me know who can work on this.

**Comment by Neeraj3508** [comment] 2020-09-28 21:06
Yes, i would love to contribute.

**Comment by shahednasser** [comment] 2020-09-29 10:21
Ok @Neeraj3508 I'll assign you. Please let me know if you need any assistance.

**Comment by Neeraj3508** [comment] 2020-09-29 10:29
@shahednasser  any deadlines?

**Comment by shahednasser** [comment] 2020-09-29 10:31
No there's no deadline @Neeraj3508 since this is just an enhancement, not a bug.

**Comment by Neeraj3508** [comment] 2020-09-29 10:33
Please can u again repeat the task exactly

**Comment by shahednasser** [comment] 2020-09-29 10:36
@Neeraj3508 we need to make social buttons consistent with the rest of the website and button types. Currently if you add `rounded-btn` to any button type it will make the button rounded. Instead of having two different classes for each social type (For example `facebook` and `facebook-rounded`) we should just add `rouneded-btn` to the social button and it will make it rounded. This will make the usage of sButtons consistent and easier to get the hang of it.

Once this is done, we can then display social buttons similar to other button styles (not rounded buttons first, rounded buttons later).

**Comment by Neeraj3508** [comment] 2020-09-29 10:38
Yes but that will create one issue that is the border radius for rounded btn class ia 25px and here as the field is long in social buttons case the curves won't be that smooth

**Comment by shahednasser** [comment] 2020-09-29 10:39
Then you can add a rule specific for `.social-btn.rounded-btn` that overrides the original border-radius rule

**Comment by Neeraj3508** [comment] 2020-09-29 10:40
Ok

**Comment by shahednasser** [comment] 2020-09-30 09:21
Issue has been resolved by code refactoring to make website more consistent. Thank you @Neeraj3508 and @dsnehasish74

**Closed by shahednasser** 2020-09-30 09:21 UTC
Labels: Priority: Medium, buttons, enhancement
